-- 12. GROUP BY
-- This is an important one.

-- 1. Count customers in each city.
select city, count(city)
from sql_practice.customers
group by city;


select * from categories;

-- 2. Count products in each category.
select category_id, count(category_id)
from sql_practice.products
group by category_id;

-- 3. Find the average product price for each category.
select category_id , avg(price)
from sql_practice.products
group by category_id;

-- 4. Find the highest product price in each category.
select category_id, max(price)
from sql_practice.products
group by category_id;

-- 5. Find the lowest product price in each category.
select category_id, min(price)
from sql_practice.products
group by category_id;

-- 6. Find total stock for each category.
select category_id, sum(stock_quantity)
from sql_practice.products
group by category_id;

-- 7. Count orders for each customer.
select customer_id, count(customer_id)
from sql_practice.orders
group by customer_id;

-- 8. Count orders for each order status.
select order_status, count(order_status)
from sql_practice.orders
group by order_status;

-- 9. Find total quantity sold for each product.
select product_id, sum(quantity)
from sql_practice.order_items
group by product_id;

-- 10. Find total revenue generated by each product.
select product_id, sum(quantity * unit_price)
from sql_practice.order_items
group by product_id;
