-- 17. Calculations
-- Practice calculated columns.
-- 1. Display product name and price after adding 10% tax.
select
	p.product_name,
    p.price as original_price,
    round(price * 0.10,2) as tax,
    round(( p.price * 1.10 ),2) as price_with_tax
from 
	sql_practice.products as p
order by
	p.product_name;
    
-- 2. Display product name and price after a 10% discount.
select
	p.product_name,
    p.price as original_price,
    price * 0.9 as Price_after_discount
from
	sql_practice.products as p
order by
	p.product_name;
    
-- 3. Calculate order-item total:
select
	sum(oi.quantity) as total_ordered_items
from 
	sql_practice.order_items as oi;
    
-- quantity × unit_price
select 
	sum( oi.quantity * oi.unit_price) as quantity_X_unit_price
from 
	sql_practice.order_items as oi;
    
-- 4. Display product name and total inventory value:
select 
	sum(p.stock_quantity)
from
	sql_practice.products as p;
    
-- price × stock_quantity
select
	p.price * p.stock_quantity
from
	sql_practice.products as p;
    
-- 5. Calculate the total value of each order.
select 
	oi.order_id,
	sum(oi.quantity * oi.unit_price)
from 
	sql_practice.order_items as oi
group by
	oi.order_id
order by
	oi.order_id
;

-- 6. Calculate revenue generated by each product.
select
	p.product_name,
    sum(oi.quantity * oi.unit_price) as total_revenue
from
	sql_practice.order_items as oi
join
	sql_practice.products as p
on
	oi.product_id = p.product_id
group by
	p.product_name
order by
	p.product_name;
    
-- 7. Calculate total revenue for all orders.
select
	sum(oi.quantity) as total_quantity,
	sum(oi.quantity * oi.unit_price) as Total_Revenue
from
	sql_practice.order_items as oi;
    
-- 8. Calculate the average order value.
select 
	avg(oi.quantity * oi.unit_price) as Average_order_value
from
	sql_practice.order_items as oi;
-- 9. Calculate the discounted price after 20% discount.
select 
	p.price,
	p.price * (1 - 0.20) as price_after_20percent_discount
from
	sql_practice.products as p;
    
-- 10. Display product name, price, stock, and total inventory value.
select 
	p.product_name,
    p.stock_quantity,
    sum(oi.quantity),
	p.stock_quantity - sum(oi.quantity) as inventory_value
from
	sql_practice.products as p
join 
	sql_practice.order_items as oi
on 
	p.product_id = oi.product_id
group by 
	p.product_name, p.stock_quantity
order by
	p.product_name;
    
    

    
    